### PR TITLE
fix(config): error when tilde is used in paths

### LINKED ISSUE #246: Config File Not Found
**Describe the bug**

The log messages indicate that my config file (in the default location) is missing.

**Version**

```console
$ gh not --version
gh-not version v0.6.1 (92248254838460978b3af005c350eba3463050b9) built at 2025-02-14T18:41:31Z
https://github.com/nobe4/gh-not/releases/tag/v0.6.1
```

**To Reproduce**

1. `gh extension install nobe4/gh-not`
2. `gh-not config --init`
3. I then modified the file created via `--init`
4. Then running `gh not sync --config=~/.config/gh-not/config.yaml` seems to not know about my config file and falls back to the default. Which is odd because this config file is technically just the default one, but modified.

**Expected behavior**

My `~/.config/gh-not/config.yaml` file to be used.

**Additional context**

Here is some console output of where I run `gh not sync` with the `--config` option pointed to my config file.

```console
$ gh not sync --config=~/.config/gh-not/config.yaml --verbosity=2
time=2025-02-14T13:59:17.599-08:00 level=WARN msg="Config file not found, using default"
Refreshing notifications...
...
..
.

$ cat ~/.config/gh-not/config.yaml
cache:
    path: /Users/birki/.local/state/gh-not/cache.json
    ttl_in_hours: 1
endpoint:
    all: true
    max_page: 5
    max_retry: 10
    per_page: 100
...
..
.
```

The config file exists, and doesn't have any errors that I know of. But the logs seem to indicate that that my config file is not found and it wants to use the default instead. I'm not sure what it means by "default" or where it is looking in this case. Seems strange...

> P.S. I only just reinstalled `gh not` and saw this shortly after trying to get it setup. Haven't been able to actually test yet though as 100% of all responses from the `/notifications` API for me today have been 502s 😢

### PR DESCRIPTION
**Pull request by nobe4**
The `~` expansion doesn't happen in `gh-not`, and should happen in the shell anyway. At least in bash & zsh, the `~` doesn't expand if it's not preceded by a space character.

In opposition, $HOME is always expanded before being sent to the program.

E.g.

```shell
# a.sh
echo $*
```

```shell
a.sh --a=~/test/a      => --a=~/test/a
a.sh --a ~/test/a      => --a /home/user/test/a
a.sh --a $HOME/test/a  => --a /home/user/test/a
a.sh --a=$HOME/test/a  => --a /home/user/test/a
```

This errors if a tilde is found in the config or cache path.

It also adds a log of the flags as they are received by `gh-not` for additional debugging.

Fix #246

### CODE REVIEW

File: internal/config/path.go [hunk 1]
```diff
@@ -16,6 +17,8 @@ const (
 	xdgStateHome   = "XDG_STATE_HOME"
 )
 
+var errTiledUsage = errors.New("tilde in path is not supported, use $HOME instead")
```
Comment (GrantBirki) [inline internal/config/path.go:20]:
```suggestion
var errTildeUsage = errors.New("tilde in path is not supported, use $HOME instead")
```

Minor typo suggestion

File: internal/config/config.go [hunk 2]
```diff
@@ -98,6 +99,10 @@ func Default(path string) (*viper.Viper, string) {
 }
 
 func New(path string) (*Config, error) {
+	if strings.HasPrefix(path, "~") {
+		return nil, fmt.Errorf("%w: config path: %s", errTiledUsage, path)
```
Comment (GrantBirki) [inline internal/config/config.go:103]:
```suggestion
		return nil, fmt.Errorf("%w: config path: %s", errTildeUsage, path)
```

File: internal/config/config.go [hunk 3]
```diff
@@ -98,6 +99,10 @@ func Default(path string) (*viper.Viper, string) {
 }
 
 func New(path string) (*Config, error) {
+	if strings.HasPrefix(path, "~") {
+		return nil, fmt.Errorf("%w: config path: %s", errTildeUsage, path)
+	}
```
Comment (ccoVeille) [inline internal/config/config.go:104]: Why forbidding it?

I would have used something like that.

```suggestion
	path, tildeFound := strings.CutPrefix(path, "~")
	if tildeFound {
		path = os.UserConfigDir() + "/" + path
	}
```

https://pkg.go.dev/os#UserConfigDir

Any reason?

Also, you could use filepath, no? Either:
- https://pkg.go.dev/path/filepath#Clean
- https://pkg.go.dev/path/filepath#Abs

It's worth trying

Or, maybe, I'm totally wrong and I'm missing something.

Comment (nobe4) [reply internal/config/config.go:104]: My reasoning is that `~`/`$HOME` expansion is the responsibility of the shell IMHO, and I don't want to have to handle it in my code. It's less logic to consider, less possibility for failures, ... :)

Now that I think about it, I think that the cache path from the configuration won't work if it has `$HOME` either, because I'm not expanding it in this code 🤔 But that would probably be better to support `$HOME` still.

Comment (nobe4) [reply internal/config/config.go:104]: I think I'll create a new PR later to support `$HOME` expansion, based on https://pkg.go.dev/os#UserHomeDir and https://pkg.go.dev/os#ExpandEnv.

That feels like an acceptable compromise to me

Comment (nobe4) [reply internal/config/config.go:104]: It does seem like `~` should be as supported as `$HOME` tho, they are both defined in the POSIX: https://pubs.opengroup.org/onlinepubs/9799919799/

Buut I don't want to do string manipulation, and since `~` is equivalent enough to `$HOME`, I'll just forbid one in favor of the other. ⚖️

Comment (nobe4) [reply internal/config/config.go:104]: Thanks for making me consider that more seriously @ccoVeille 🌷 📖

Comment (nobe4) [reply internal/config/config.go:104]: cc https://github.com/nobe4/gh-not/pull/250

Comment (ccoVeille) [reply internal/config/config.go:104]: > But I don't want to do string manipulation, and since ~ is equivalent enough to $HOME, I'll just forbid one in favor of the other. ⚖️

Please adapt the tilde error message to suggest using $HOME

Comment (nobe4) [reply internal/config/config.go:104]: Already in https://github.com/nobe4/gh-not/pull/247/files#diff-dd7b39f2e0f33d3ad65c6be4bbc45b531d870ea2811bc82768d2ff0c57b463eaR20
